steps:
  # install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements-test.txt", "--user"]

  - name: python
    entrypoint: /bin/sh
    env: ["PATH=/builder/home/.local/bin:$$PATH"]
    # args: ["-m", "pytest", "-s", "dags/"]
    args:
    - -c
    - |-
      echo $$PATH

options:
  logging: CLOUD_LOGGING_ONLY
