steps:
  # install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements-test.txt", "--user"]

  - name: python
    env:
    - "PATH=/builder/home/.local/bin:$$PATH"
    script: |
      #!/usr/bin/env bash
      python -m pytest -s dags/

options:
  logging: CLOUD_LOGGING_ONLY
